feat(5): added config test
sgtxn/anio pull request #11
Opened 2023-02-02 17:30 UTC by HoshinoHideki

There's been a couple of issues along the way:

1. I'm not sure if it's possible to write a single test that would test loading config from both windows and linux and that would work from both windows and linux. So I guess we'll need to write separate tests for other platforms? 
2. I couldn't think of a way to test for specific errors. Rather, I'm not sure how to properly assert them when they happen. I can *make* them happen with a corrupt JSON file or an invalid filepath, but then the test simply fails. Need advice.
3. I tried to keep it DRY and write a sub-function to run the test twice instead of copy-pasting the same lines of code, but couldn't make it work. Any suggestions on syntax/structure?

2023-02-02 20:53 UTC, sgtxn commented
1. Nah, this test as it is should work just fine under both linux and windows, so no need to do anything else here.
2. Yep, cause all the errors in `config` package always end up in a `log.Fatal` statement, which kills the application and fails the test. This is one of the reasons why we shouldn't be doing that, and instead errors should be wrapped and returned to top level (`main` in our case), where they would be handled. As a side effect - this will make testing for specific errors pretty simple and straightforward.
3. Try taking a look at [table-driven tests](https://dev.to/boncheff/table-driven-unit-tests-in-go-407b). The idea is that you have an array of test cases with setup/input/expectations and then you iterate over them and execute every single one. Pro-tip: setup can be a function.

2023-02-02 21:10 UTC, sgtxn commented on config/config_test.go
> +		assert.True(t, len(param) > 0)
This is a bit too generic, try to accert config fields against some specific values rather than just check their type and string length

2023-02-02 21:12 UTC, sgtxn commented on config/config_test.go
> +func deleteConfigFile(filepath string) {
There isn't really much point in extracting such a simple and straightforward code into a separate function

2023-04-15 21:45 UTC, sgtxn commented on config/config.go
> +	configFileName = "config.json"
You use "config.json" at least 3 times in this package, might be a good idea to declare it as a global const instead

2023-04-15 21:48 UTC, sgtxn commented on config/config.go
> +		configFolder += "/Anio/"
Windows uses `\` as path separators while linux and macos use `/`.  
This might work, but stdlib has some cool things to deal with os-specific paths, such as [this function](https://pkg.go.dev/path/filepath#Join), so it might make sense to use it.

2023-04-15 21:57 UTC, sgtxn commented on config/config.go
>  	conf := Config{}
Try not to initialize variables earlier than you need.  
In this example you create a `conf` variable, but then do something completely unrelated, and only four lines later you actually use it. It would make more sense to create it right before using.

2023-04-15 22:00 UTC, sgtxn commented on config/config.go
> +	_, err := os.Stat(folderPath)
You could reuse `exists` function here

2023-04-17 17:51 UTC, HoshinoHideki commented on config/config.go
> +	_, err := os.Stat(folderPath)
Turns out exists() doesn't return true if filepath is a folder! I'll get to fixing that...

2023-05-05 23:14 UTC, HoshinoHideki commented on config/config_test.go
> +var testDirectory = filepath.Join(workDirectory, "tests")
Figured we can put any files we create during test process right in the working folder (and then delete it afterwards).

2023-05-05 23:15 UTC, HoshinoHideki commented on config/config_test.go
> +var wrongDirectory = "A://bcdefg/" //bogus filepath for testing purposes
Not sure if there's a better way but for now it's something that should work on any platform(?)

2023-05-05 23:19 UTC, HoshinoHideki commented on config/config_test.go
> +	// 	name:        "Wrong Json File",
This was supposed to replace the config .json data with gibberish and result in an error... which it didn't.

Turns out it will eat any JSON and if it doesn't have OS\User data it will remain empty, without producing an error.
Which means I'll have to fix my code  and add some data checking\erroring.

2023-05-05 23:24 UTC, HoshinoHideki commented on config/config_test.go
> +				"loading":  loadExistingConfig,
Not sure if this is too confusing. This will loop both subfunctions through the same set of tests. But it may be unnecessary\not too well-implemented.

2023-05-05 23:26 UTC, HoshinoHideki commented on config/config_test.go
> +				// unused piece of code, might become handy later.
This is where the JSON would be "corrupted" manually if the wrongData flag was to be set true.

The code itself works and corrupts data fine, but since it doesn't error out, when the conf struct gets tested it obviously doesn't pass, since it's empty and it wasn't caught by the package code.

2023-05-05 23:31 UTC, HoshinoHideki commented on config/config_test.go
> +// TestLoad: tests the main function as a whole.
Here's the most frustrating part.

I tried to find a way to tinker with runtime.GOOS and file permissions to simulate situations when the code is getting run by on different platforms or the system can't get access to the file, but it didn't work.

I guess we can ignore simulating the unsupported OS test case, but it must be possible to permission-lock a file in a way that will make the package error out. I just don't know (yet) how to do it.

2023-05-05 23:33 UTC, HoshinoHideki commented on config/config_test.go
> +	configFolderPath, _ := os.UserConfigDir()
This is to check if a config file already exists and back it up.

Just in case.

2023-05-05 23:41 UTC, HoshinoHideki commented on config/config_test.go
> +			assert.NoError(t, err)
Helper function doesn't work here because it pulls a global var that thinks conf file is in the test folder.
I'll get to fixing that... meanwhile it just repeats the same code.

2023-05-06 08:36 UTC, sgtxn commented on config/config_test.go
> +var testDirectory = filepath.Join(workDirectory, "tests")
Yep, sounds like a nice idea

2023-05-06 08:48 UTC, sgtxn requested changes

2023-05-06 08:48 UTC, sgtxn commented on config/config_test.go
> +				os.Mkdir(testDirectory, os.ModeDir)
`os.ModeDir` is being used a bit incorrectly here. [It exists to be compared with when checking that some file is a directory](https://stackoverflow.com/questions/70465320/os-stat-permission-denied-errorsyscall-errno-eacces-13), not to be used as a permission. Due to this, the test creates a `tests` directory with 000 permissions (on linux) which it cannot write to, so the next line fails with an error.  
Just use something like 0644 here.

2023-05-06 09:00 UTC, sgtxn requested changes

2023-05-06 09:00 UTC, sgtxn commented on config/config_test.go
> +
This test also fails on linux due to the same incorrect `os.Mkdir` usage in `createDefaultConfig` function, which creates an unwritable folder.  
With proper permissions the test runs fine.

2023-06-05 15:04 UTC, HoshinoHideki commented on config/config.go
> +	// check here that it has data.
I know checking manually every field is subpar, but I'm not sure how to iterate through a custom struct without importing extra packages.

Maybe rewrite it later, when cfg is much bigger and has a lot of parameters to check?

2023-06-30 13:07 UTC, merged